config/routes.rb
TheCube::Application.routes.draw do

  # routes injected by other libraries
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # root
  root to: "main#home"
  
  # main pages
  get "about", to: "main#about"
  get "join", to: "main#join"
  get "calendar", to: "main#calendar"

  # member and company profiles
  resources :companies, :only => [:index, :show]
  resources :members, :only => [:index, :show]
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, 
	:recoverable, :rememberable, :trackable, :validatable

	# == callbacks
	before_save :compile_email_hash

	# == methods
	def compile_email_hash
		if defined? self.email_hash
			self.email_hash = Digest::MD5.hexdigest(self.email)
		end
	end

	def compile_email_hash!
		if defined? self.email_hash
			self.email_hash = Digest::MD5.hexdigest(self.email)
			self.save
		end
	end

	# a convenience method for getting the admin users's full name
	def full_name
		if self.last_name
			return self.first_name + " " + self.last_name
		elsif self.first_name
			return self.first_name
		else
			return nil
		end
	end

	# returns a url which can be used as the src attribute in an img tag
	# powered by gravatar
	# http://en.gravatar.com/site/implement/images/ruby/
	def profile_image_url(size=400)
		"http://www.gravatar.com/avatar/#{self.email_hash}?size=#{size}"
	end
end

app/models/company.rb
class Company < ActiveRecord::Base
	# == relations
	has_and_belongs_to_many :members
	has_and_belongs_to_many :posts

	# == validations
	validates :name, presence: true
	validates :blurb, presence: true
	validates :founded_at, presence: true
	validate :founded_at_cannot_be_in_the_future
	validates :logo, presence: true, url: true
	validates :site_url, url: {allow_blank: true}

	def founded_at_cannot_be_in_the_future
		errors.add(:founded_at, "can't be in the future") if
      	!founded_at.blank? and founded_at > Date.today
	end
end

app/models/member.rb
require 'digest/md5' # used for hashing the email

class Member < ActiveRecord::Base
	# == relations
	has_and_belongs_to_many :companies
	has_and_belongs_to_many :posts

	# == validations
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, format: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
	validates :personal_site_url, url: {allow_blank: true}

	# == callbacks
	before_save :auto_format, :compile_email_hash

	# == methods
	def auto_format
		self.first_name = self.first_name.capitalize
		self.last_name = self.last_name.capitalize
	end

	def compile_email_hash
		self.email_hash = Digest::MD5.hexdigest(self.email)
	end

	def compile_email_hash!
		self.email_hash = Digest::MD5.hexdigest(self.email)
		self.save
	end

	# a convenience method for getting the member's full name
	def full_name
		self.first_name + " " + self.last_name
	end

	# returns a url which can be used as the src attribute in an img tag
	# powered by gravatar
	# http://en.gravatar.com/site/implement/images/ruby/
	def profile_image_url(size=400)
		"http://www.gravatar.com/avatar/#{self.email_hash}?size=#{size}"
	end
end

app/models/post.rb
require "bluecloth"

class Post < ActiveRecord::Base
	include ActionView::Helpers::DateHelper

	# == relations
	belongs_to :author, :class_name => "AdminUser", :foreign_key => "admin_user_id"
	has_and_belongs_to_many :companies
	has_and_belongs_to_many :members

	# == validations
	validates :heading, presence: true
	validates :markdown_content, presence: true
	validates :author, presence: true

	# == callbacks
	before_save :auto_titleize, :compile_content

	# == scopes
	default_scope order("pinned desc, created_at desc")

	# == methods
	def auto_titleize
		self.heading = self.heading.titleize
	end

	def compile_content
		self.html_content = BlueCloth.new(self.markdown_content).to_html
	end

	def compile_content!
		self.html_content = BlueCloth.new(self.markdown_content).to_html
		self.save
	end

	def tags
		tags = []
		self.members.each do |m|
			tags << {:name => m.full_name, :url => Rails.application.routes.url_helpers.member_path(m)}
		end
		self.companies.each do |c|
			tags << {:name => c.name, :url => Rails.application.routes.url_helpers.company_path(c)}
		end
		return tags
	end

	def formatted_date
		if (self.created_at > 2.days.ago)
			return time_ago_in_words(self.created_at) << " ago"
		else 
			return self.created_at.strftime("%A, %b %d")
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

	def index
		@companies = Company.all
	end

	def show
		@company = Company.find params[:id]
	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def home
	end

	def about
	end

	def join
	end

	def gallery
	end

	def calendar
	end

	def contact
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

	def index
		@members = Member.all
	end

	def show
		@member = Member.find params[:id]
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/companies/_company.html.erb
<!-- 
	This should be a small card-like element that shows some basic info
	about each company.
-->
<div class="content-company clearfix col-lg-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="company-logo">
				<% if company.closed? %>
				<div class="closed">
					Closed
				</div>
				<% end %>
				<%= link_to company do %>
				<%= image_tag company.logo %>
				<% end %>
			</div>
		</div>
		<div class="company-profile clearfix">
			<div class="company-name">
				<h1><%= link_to company.name, company %></h1>
			</div>
			<div class="company-members">
				<%= (company.members.map{|m| link_to m.full_name, m}).join(" | ").html_safe %>
			</div>
			<div class="company-description">
				<%= company.blurb %>
			</div>
		</div>
	</div>
</div>

app/views/companies/index.html.erb
<h1>Companies:</h1>

<% @companies.each do |c| %>
	<%= render c %>
<% end %>

app/views/companies/show.html.erb
<div class="company">
	<div class="company-header">
		<a class="navbar-toggle sidebar-toggle" data-toggle="collapse" data-target="#sidebar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</a>
		<div class="company-logo">
			<% if @company.closed? %>
			<div class="closed">
				Closed
			</div>
			<% end %>
			<img src="<%= @company.logo %>">
		</div>
		<div class="company-name">
			<% if !@company.site_url.blank? %>
			<h1><%= @company.name %></h1>
			<% else %>
			<h1><%= link_to @company.name, @company.site_url %></h1>
			<% end %>
		</div>
		<div class="company-info">
			<!-- Founded on <%= @company.founded_at %> -->
			<%= (@company.members.map{|m| link_to m.full_name, m}).join(" | ").html_safe %>
		</div>
		<div class="company-blurb">
			<p>
				<%= @company.blurb %>
			</p>
		</div>
	</div>
	<div class="company-posts">
		<% if @company.posts.any? %>
			<% @company.posts.each do |p| %>
				<%= render p %>
			<% end %>
		<% else %>
			<div class="no-posts">
				No recent posts for this company.
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Cube</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,300,700,800' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" href="favicon.ico"/>
</head>
<body>

	<%= render 'main/sidebar' %>
	<div class="content">

		<%= yield %>

	</div>

</body>
</html>

app/views/main/_header_image.html.erb
<div class="header-image">
	<a class="navbar-toggle sidebar-toggle" data-toggle="collapse" data-target="#sidebar">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</a>
	<%= image_tag "header-image-1.jpg" %>
</div>

app/views/main/_mailchimp.html.erb
<div id="mc_embed_signup">
	<form action="http://incube.us6.list-manage.com/subscribe/post?u=48d541d348&amp;id=89e4f3d304" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>

		<div class="mc-field-group form-group">
			<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
			</label>
			<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
		</div>
		<div class="mc-field-group form-group">
			<label for="mce-FNAME form-input">First Name </label>
			<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
		</div>
		<div class="mc-field-group form-group">
			<label for="mce-LNAME">Last Name </label>
			<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
		</div>
		<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
		<div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
		<div style="position: absolute; left: -5000px;"><input type="text" name="b_48d541d348_89e4f3d304" value=""></div>
		<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
	</form>
</div>

app/views/main/_rush_mailchimp.html.erb
<div id="mc_embed_signup">
	<form action="http://incube.us6.list-manage.com/subscribe/post?u=48d541d348&amp;id=89e4f3d304" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>

		<div class="mc-field-group form-group">
			<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
			</label>
			<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
		</div>
		<div class="mc-field-group form-group">
			<label for="mce-FNAME form-input">First Name </label>
			<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
		</div>
		<div class="mc-field-group form-group">
			<label for="mce-LNAME">Last Name </label>
			<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
		</div>
		<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
		<div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
		<div style="position: absolute; left: -5000px;"><input type="text" name="b_48d541d348_89e4f3d304" value=""></div>
		<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
	</form>
</div>

app/views/main/_sidebar.html.erb
<div class="sidebar" class="panel" role="navigation">
	<ul>
		<div class="logo">
			<%= link_to "/" do %>
			<%= image_tag "logo.svg" %>
			<% end %>
		</div>
		<li class="<%= 'active' if params[:action] == 'home' %>"><%= link_to "Home", "/" %></li>
		<li class="<%= 'active' if params[:action] == 'about' %>"><%= link_to "About Us", about_path %></li>
		<% if  params[:action] == 'about' %>
		<ul class="submenu">
			<li class="active"><a href="#mission">Mission</a></li>
			<li><a href="#members">Members</a></li>
			<li><a href="#companies">Companies</a></li>
			<li><a href="#special-thanks">Special Thanks</a></li>
		</ul>
		<% end %>
		<li class="<%= 'active' if params[:action] == 'join' %>"><%= link_to "Join Us", join_path %></li>
		<li class="<%= 'active' if params[:action] == 'calendar' %>"><%= link_to "Rush Calendar", calendar_path %></li>
	</ul>
	<div class="social">
		<a href="https://www.facebook.com/thecubeduke"><button href="https://www.facebook.com/dukeincube" class="facebook"><img src="/images/fb.svg"></button></a>
		<button class="home"><img src="/images/home.svg"></button>
		<a href="mailto:ibanca.anand@duke.edu"><button class="email"><img src="/images/email.svg"></button>
		</a>
		<div class="address">
			205 Alexander Avenue
			<br>
			Room D
			<br>
			Durham, NC 27708
		</div>
	</div>
</div>

app/views/main/_special_thanks.html.erb
<div class="content-company clearfix col-lg-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="company-logo">
			<%= image_tag "howie.jpg" %>
		</div>
		</div>
		<div class="company-profile clearfix">
			<div class="company-name">
				<h1>Howie Rhee</h1>
			</div>
			<div class="company-description">
				Managing Director Of Entrepreneurship | Advisor of The Cube
			</div>
		</div>
	</div>
</div>

<div class="content-company clearfix col-lg-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="company-logo">
			<%= image_tag "judd.jpg" %>
		</div>
		</div>
		<div class="company-profile clearfix">
			<div class="company-name">
				<h1>Judd Staples</h1>
			</div>
			<div class="company-description">
				Director of Strategy and Operations of The Duke I&E Initiative
			</div>
		</div>
	</div>
</div>

<div class="content-company clearfix col-lg-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="company-logo">
			<%= image_tag "eric.jpg" %>
		</div>
		</div>
		<div class="company-profile clearfix">
			<div class="company-name">
				<h1>Eric Toone</h1>
			</div>
			<div class="company-description">
				Director of The Duke I&E Initiative
			</div>
		</div>
	</div>
</div>

<div class="content-company clearfix col-lg-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="company-logo">
			<%= image_tag "toby.png" %>
		</div>
		</div>
		<div class="company-profile clearfix">
			<div class="company-name">
				<h1>Tobias Walter</h1>
			</div>
			<div class="company-description">
				CFO & COO of Shoeboxed | Mentor to The Cube
			</div>
		</div>
	</div>
</div>

<div class="content-company clearfix col-lg-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="company-logo">
			<%= image_tag "kimberly.jpg" %>
		</div>
		</div>
		<div class="company-profile clearfix">
			<div class="company-name">
				<h1>Kimberly Jenkins</h1>
			</div>
			<div class="company-description">
				Senior Advisor, Ex-Officio of The Duke I&E Initiative
			</div>
		</div>
	</div>
</div>

<div class="content-company clearfix col-lg-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="company-logo">
			<%= image_tag "jesse.jpg" %>
		</div>
		</div>
		<div class="company-profile clearfix">
			<div class="company-name">
				<h1>Jesse Lipson</h1>
			</div>
			<div class="company-description">
				Founder/CEO of Sharefile | Mentor to The Cube
			</div>
		</div>
	</div>
</div>

<div class="content-company clearfix col-lg-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="company-logo">
			<%= image_tag "brooks.png" %>
		</div>
		</div>
		<div class="company-profile clearfix">
			<div class="company-name">
				<h1>Brooks Bell</h1>
			</div>
			<div class="company-description">
				CEO/Founder of Brooks Bell | Mentor to The Cube
			</div>
		</div>
	</div>
</div>

<div class="content-company clearfix col-lg-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="company-logo">
			<%= image_tag "joe.jpg" %>
		</div>
		</div>
		<div class="company-profile clearfix">
			<div class="company-name">
				<h1>Joe Davy</h1>
			</div>
			<div class="company-description">
				CEO of Buystand | Mentor to The Cube
			</div>
		</div>
	</div>
</div>

app/views/main/_updates_mailchimp.html.erb
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
	<form action="http://incube.us6.list-manage1.com/subscribe/post?u=48d541d348&amp;id=6bd1ead573" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
		<div class="mc-field-group form-group">
			<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
			</label>
			<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
		</div>
		<div class="mc-field-group form-group">
			<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
			</label>
			<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
		</div>
		<div class="mc-field-group form-group">
			<label for="mce-LNAME">Last Name  <span class="asterisk">*</span>
			</label>
			<input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
		</div>
		<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
		<div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
		<div style="position: absolute; left: -5000px;"><input type="text" name="b_48d541d348_6bd1ead573" value=""></div>
		<div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
	</form>
</div>

<!--End mc_embed_signup-->

app/views/main/about.html.erb
<%= render "header_image" %>
<div class="content-mission" id="mission" name="mission">
	<div class="mission-hero">
		The Cube is Duke's student-run, entrepreneurial residential community. We yearn to make a difference, are driven to execute upon and deliver great ideas and are dedicated to learning and growing.	
	</div>
	<div class="mission-title">
		<h1>What do we expect from our members?</h1>
	</div>
	<div class="mission-body">
		<ol>
			<li>
				Produce a product or service that is iterable and can be brought to the general market, whether via non-profit or for-profit venture. The Cube is also dedicated to promoting entrepreneurship of any form within the community and on Duke’s campus, including social ventures.
			</li>
			<li>
				Timeline for development:
				<ol>
					<li>
						Within the first year following a member’s induction, they are expected to work to produce a product or venture.
					</li>
					<li>
						Within a member’s time in The Cube, they are expected to launch at least 1 product or venture
					</li>
				</ol>
			</li>
		</ol>
	</div>		
</div>
<div class="content-members clearfix" id="members" name="members">
	<h1 class="section-header">Members</h1>
	<% Member.where(alumni: false).all.each do |m| %>
	<%= render m %>
	<% end %>
	<% Member.where(alumni: true).all.each do |m| %>
	<%= render m %>
	<% end %>
</div>
<div class="content-companies clearfix" id="companies" name="companies">
	<h1 class="section-header">Companies</h1>
	<% Company.all.each do |c| %>
	<%= render c %>
	<% end %>
</div>
<div class="content-companies clearfix" id="special-thanks" name="special-thanks">
	<div class="mission-hero">
		The Cube wants to thank all Duke alumni entrepreneurs and Duke faculty and staff for being helpful mentors and supporting us in all that we do. We couldn't have gotten to where we are today without you guys! Here are just a few of those amazing people!	
	</div>
	<%= render "special_thanks" %>
</div>

app/views/main/calendar.html.erb
<%= render "header_image" %>
<div class="content-calendar">
	<!-- <div class="calendar-mission">
		<div class="mission-hero">
			The Cube believes giving back to the Duke community. This is why we hold events like Dinner Days with Duke Entrepreneurs and Demo Day, in hopes to expose our peers to entrepreneurship, encourage them to think like entrepreneurs and motivate them to be entrepreneurs.
		</div>
		<div class="mission-inquiry">
			<h1>Are you a Duke alumni or current entreprenur?</h1>
			If the sound of meeting and getting to know student entrepreneurs over dinner seems interesting to you, shoot us an email! We would love to arrange your visit to Duke University and have dinner with you!
		</div> -->
		<div class="calendar-mission">
		<div class="mission-hero text-center" >
			Are you interested in joining the Cube? Find our rush calendar here. 
		</div>
</div>

	<div class="calendar">
		<a href="https://www.facebook.com/thecubeduke?fref=photo"><img src="https://scontent-b-ord.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/10345822_723935091047135_4537972516596889359_n.jpg?oh=f0fe0846e0d67840ebd263de0c38616e&oe=55210DE8" style = "width: 100%"></a>
	</div>
</div>
<div class="content-sidebar">
	<div class="sidebar-widget">
		<div class="widget-title">
			Rush Events Mailing List
		</div>
		<div class="widget-body">
			<%= render "rush_mailchimp" %>
		</div>
	</div>
	<div class="sidebar-widget">
		<div class="widget-title">
			General Events Mailing List
		</div>
		<div class="widget-body">
			<%= render "updates_mailchimp" %>
		</div>
	</div>
</div>

app/views/main/home.html.erb
<div class="content-posts">
	<% Post.all.limit(10).each do |p| %>
	<%= render p %>
	<% end %>
</div>
<div class="content-sidebar">
	<div class="sidebar-widget">
		<div class="widget-title">
			Upcoming Events
		</div>
		<div class="widget-body">
			<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showTz=0&amp;showNav=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=dukeincube%40gmail.com&amp;color=%23060D5E&amp;ctz=America%2FNew_York" style=" border-width:0 " width="100%" height="300" frameborder="0" scrolling="no"></iframe>
		</div>
	</div>
	<div class="sidebar-widget">
		<div class="widget-title">
			Get Rush Updates!
		</div>
		<div class="widget-body">
			<%= render "rush_mailchimp" %>
		</div>
	</div>
</div>

app/views/main/join.html.erb
<%= render "header_image" %>
<div class="content-join">
	<div class="join-mission">
		<div class="mission-hero">
			The Cube looks for students who are self-driven, hard-working and not to mention, fun to hang out with. Community and friendship is the core of The Cube experience. We are all about supporting each other, whether it be honing business pitches, late night product design and development or sorting through piles of market research.
		</div>
		<div class="mission-process">
		<h1>The Cube's Spring Rush Process</h1>
		<p>Every spring, The Cube joins the SLG rush process to find new members to join our community. Our rush process works like this: </p>
		<ol>
			<li>
				Three weeks of planned events and activities
			</li>
			<li>One Application</li>
			<li>One Interview</li>
			<li>A few awesome additions to The Cube!</li>
		</ol>
		<p>There are two types of events:</p>
		<ol>
			<li>
				<strong>Open Events</strong>
				<p>These are events in the beginning week and a half of rush, like the two open houses, Nerf Gun War and movie night. By making sure that you sign in, attend and talk to us during these events, you become more likely to be invited to the more selective events.</p>
			</li>
			<li>
				<strong>Invitation-Only Events</strong>
				<p>
					These are events that are more selective, mostly due to the nature and expense of the event. Some examples are: Dinner With Duke Alumni Entrepreneurs, Tea at the WaDuke and The Money Challenge.
				</p>
			</li>
		</ol>
	</div>
	</div>
</div>
<div class="content-sidebar">
	<div class="sidebar-widget">
		<div class="widget-title">
			Get Rush Info and Updates!
		</div>
		<div class="widget-body">
			<%= render "rush_mailchimp" %>
		</div>
	</div>
</div>

app/views/members/_member.html.erb
<!-- 
	This should be a small card-like element that shows some basic info
	about each member.
-->
<div class="content-member col-lg-4 col-md-6">
	<div class="thumbnail">
		<div class="pull-left">
			<div class="member-photo">
				<% if member.alumni? %>
				<div class="alumni">
					Alumni
				</div>
				<% end %>
				<%= link_to member do %>
				<% if member.profile_picture_url != nil %>
				<%= image_tag member.profile_picture_url %>
				<% else %>
				<%= image_tag member.profile_image_url(800) %>
				<% end %>
				<% end %>
			</div>
		</div>
		<div class="member-profile caption clearfix">
			<div class="profile-name">
				<h1><%= link_to member.full_name, member %></h1>
			</div>
			<div class="profile-info">
				<%= (member.companies.map{|c| link_to c.name, c}).join(" ").html_safe %>
			</div>
		</div>
	</div>
</div>

app/views/members/index.html.erb
<h1>Members:</h1>

<% @members.each do |m| %>
	<%= render m %>
<% end %>

app/views/members/show.html.erb
<div class="member">
	<div class="member-header">
		<a class="navbar-toggle sidebar-toggle" data-toggle="collapse" data-target="#sidebar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</a>
		<div class="member-photo">
			<% if @member.alumni? %>
			<div class="alumni">
				Alumni
			</div>
			<% end %>
			<% if @member.profile_picture_url != nil %>
			<%= image_tag @member.profile_picture_url %>
			<% else %>
			<%= image_tag @member.profile_image_url(800) %>
			<% end %>
		</div>
		<div class="member-name">
			<h1><%= @member.full_name %></h1>
		</div>
		<div class="member-info">
			<%= @member.email %>
			<% if !@member.personal_site_url.blank? %>
			<br/>
			<%= link_to @member.personal_site_url, @member.personal_site_url %>
			<% end %>
			<br/>
			<%= (@member.companies.map{|c| link_to c.name, c}).join(" | ").html_safe %>
		</div>
	</div>
	<div class="member-posts">
		<% if @member.posts.any? %>
		<% @member.posts.each do |p| %>
		<%= render p %>
		<% end %>
		<% else %>
		<div class="no-posts">
			No recent posts for this member.
		</div>
		<% end %>
	</div>
</div>

app/views/posts/_post.html.erb
<div class="content-post">
	<% if post.pinned? %>
		<div class="pinned">Pinned Post</div>
	<% end %>
	<div class="post-title">
		<img src="<%= post.author.profile_image_url(200) %>">
		<h1><%= post.heading %></h1>
	</div>
	<div class="post-author-time">
		<%= post.author.full_name %> | <%= post.formatted_date %>
	</div>
	<div class="post-tags">
		<span>Tags: </span>
		<% if post.tags.any? %>
			<% post.tags.each do |t| %>
				<%= link_to t[:url] do %>
					<span class="label label-primary post-tag">
						<%= t[:name] %>
					</span>
				<% end %>
			<% end %>
		<% else %>
			<em>none</em>
		<% end %>
	</div>
	<div class="post-body">
		<%= post.html_content.html_safe %>
	</div>
</div>